import http from 'node:http';
import {URL} from 'node:url';
import mqtt from 'mqtt';
const port=Number(process.env.PORT||8787);const relays=['pump','zone1','lighthome','lightsala'];
const publishTopics=['smartfarm/relay/{relay}/set','smartfarm/relay/{relay}/timer/set','smartfarm/schedule/{relay}/set','smartfarm/emergency/set','smartfarm/config/telegram/set','smartfarm/config/telegram/test','smartfarm/reminder/set','smartfarm/ai/alert/set'];
const subscribeTopics=['smartfarm/status/online','smartfarm/device/status','smartfarm/sensor/dht11','smartfarm/emergency/status','smartfarm/config/telegram/status','smartfarm/reminder/status','smartfarm/ai/alert/status',...relays.flatMap(r=>[`smartfarm/relay/${r}/status`,`smartfarm/relay/${r}/timer/status`,`smartfarm/schedule/${r}/status`])];
const snapshot=new Map();let client=null;let connected=false;
if(process.env.MQTT_URL){client=mqtt.connect(process.env.MQTT_URL,{username:process.env.MQTT_USERNAME,password:process.env.MQTT_PASSWORD,clientId:process.env.MQTT_CLIENT_ID||`gaden-dashboard-${Date.now()}`,rejectUnauthorized:process.env.MQTT_REJECT_UNAUTHORIZED!=='false',reconnectPeriod:5000});client.on('connect',()=>{connected=true;client.subscribe(subscribeTopics)});client.on('close',()=>connected=false);client.on('message',(topic,payload)=>snapshot.set(topic,payload.toString()));client.on('error',()=>connected=false)}
function auth(req){const token=req.headers['x-dashboard-token']||'';if(process.env.ADMIN_TOKEN&&token===process.env.ADMIN_TOKEN)return{authenticated:true,role:'admin'};if(process.env.DASHBOARD_TOKEN&&token===process.env.DASHBOARD_TOKEN)return{authenticated:true,role:'operator'};return{authenticated:!process.env.DASHBOARD_TOKEN&&!process.env.ADMIN_TOKEN,role:process.env.DASHBOARD_TOKEN||process.env.ADMIN_TOKEN?'viewer':'operator'}}
function json(res,status,data){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-origin':'*'});res.end(JSON.stringify(data))}
function allowedTopic(topic){const parts=topic.split('/');if(parts.length<4||parts[0]!=='smartfarm')return false;if(topic==='smartfarm/emergency/set'||topic.startsWith('smartfarm/config/telegram/')||topic==='smartfarm/reminder/set'||topic==='smartfarm/ai/alert/set')return true;return relays.includes(parts[2])&&(parts[3]==='set'||(parts[3]==='timer'&&parts[4]==='set')||(parts[1]==='schedule'&&parts[3]==='set'))}
const server=http.createServer((req,res)=>{const u=new URL(req.url,`http://${req.headers.host}`);const role=auth(req);
 if(req.method==='GET'&&u.pathname==='/api/mqtt/state')return json(res,200,{state:Object.fromEntries(snapshot),connected,auth:role,configured:Boolean(client)});
 if(req.method==='GET'&&u.pathname==='/api/mqtt/health')return json(res,200,{connected,configured:Boolean(client),auth:role});
 if(req.method==='POST'&&u.pathname==='/api/auth/token'){let body='';req.on('data',c=>body+=c);req.on('end',()=>{try{const {token}=JSON.parse(body);const next=auth({headers:{'x-dashboard-token':token}});return json(res,next.authenticated?200:401,next)}catch{return json(res,400,{error:'invalid request'})}});return}
 if(req.method==='POST'&&u.pathname==='/api/mqtt/publish'){if(!role.authenticated||role.role==='viewer')return json(res,403,{error:'ต้องมีสิทธิ์ควบคุมอุปกรณ์'});let body='';req.on('data',c=>body+=c);req.on('end',()=>{try{const {topic,payload}=JSON.parse(body);if(!allowedTopic(topic))return json(res,400,{error:'topic not allowed'});if(!connected||!client)return json(res,503,{error:'MQTT disconnected'});client.publish(topic,String(payload));return json(res,202,{accepted:true,role:role.role})}catch{return json(res,400,{error:'invalid request'})}});return}
 res.writeHead(404);res.end()});server.listen(port);
